# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: cr.yandex/crp81e38d37pnpqa41ti/dds_service   # cr.yandex/crpe7gmtkh8el8rkf2ub cr.yandex/crp81e38d37pnpqa41ti/stg_service:v2024-08-31-r1

  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2024-09-04-r1"

containerPort: 5000

config:

  KAFKA_HOST: "rc1a-tpkqnslavk1nvb1p.mdb.yandexcloud.net"
  KAFKA_PORT: "9091"
  KAFKA_CONSUMER_USERNAME: "producer_consumer"
  KAFKA_CONSUMER_PASSWORD: "mazzal25"
  KAFKA_CONSUMER_GROUP: "consumer_group"
  KAFKA_SOURCE_TOPIC: "stg-service_orders"
  KAFKA_DESTINATION_TOPIC: "dds_service_orders"

  PG_WAREHOUSE_HOST: "rc1a-zsr0k72ghdzvn2e2.mdb.yandexcloud.net"
  PG_WAREHOUSE_PORT: "6432"
  PG_WAREHOUSE_DBNAME: "ya_db"
  PG_WAREHOUSE_USER: "mazzal"
  PG_WAREHOUSE_PASSWORD: "mazzal25"

  REDIS_HOST: "c-c9q7g5v8p6bd57e82ip1.rw.mdb.yandexcloud.net"
  REDIS_PORT: "6380"
  REDIS_PASSWORD: "mTG9GD5XruDQcqi"



imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
